### ISSUE TITLE
Unreliable firmware update when using iPhone 11/iOS 16.1

### ISSUE THREAD

**Issue by dmeehan1968** [Lora-net/SWSD004#1]
Recently took delivery of two LR1110TRK1BKS.  

Downloaded LoRa Edge Config from Apple App Store (v2) to iPhone 11 running iOS 16.1.

Initial setup suggested upgrade of firmware to latest versions, but when driven from the iOS app the firmware updates, of either tracker app or the LR1110 firmware, typically failed.  Repeated retries eventually managed to succesfully apply.

When the failure occurs, the device is left in OTA mode and the only option after BLE connect is to reapply the Modem-E tracker firmware, which invariably fails, but repeated attempts eventually get a successful firmware update.

If the device is switched to the LBM tracker, this always fails and leaves the device in OTA mode, and requires repeated application of the Modem-E tracker to regain normal function.  This might just be because firmware updates generally fail and the iPhone app only offers update of the Modem-E tracker, which makes the recovery process long winded and not worth re-attempting.

When using an Android device (Sony Xperiod L4) upgrade of the tracker applications and LR1110 worked perfectly on one device, and experienced a single failure on the other device when migrating to LBM tracker.  This left the device in OTA mode, but the Android app allowed direct migration again which was successful on the second attempt.

**Comment by smtcbboulet** [comment]
Hello,

Unfortately we are aware of this issue and we knonw that it depends on the smartphone/iOS/Android version, the good thing it's that it's fixed on both applications (iOS and Android). Both versions should be release in the next two weeks.

Regards,

Ben

**Comment by dmeehan1968** [comment]
@smtcbboulet Would be super helpful if this could be documented somewhere highly visible.  I wasted quite a bit of time on the update failures and then trying to work with the v1 app when v2 was really what I needed all along.

**Comment by smtcbboulet** [comment]
Hello, the lora edge config application have been updated and released on the stores.
