### ISSUE TITLE
Question in regards to tracking applications using this SDK example

### ISSUE THREAD

**Issue by ZenoMaverick** [Lora-net/SWSD004#3]
Hi, I have a question with regards to a tracking application that I am interested to work on but want to clarify using this SDK.

**How many uplink messages are needed to get one set of position data from the application server. Say for example using the LoRaCloud Modem and Geolocation Services?**

I'm curious how it handles in an environment where end devices are far from the gateway and messages may be dropped as they are not received by the gateway. I'm guessing the answer is that each GNSS scan must contain all the satellite information data. Is this correct?

**Comment by smtcbboulet** [comment]
Hello : 

**_How many uplink messages are needed to get one set of position data from the application server. Say for example using the LoRaCloud Modem and Geolocation Services?_**
In fact only 1 uplink can give you a position. today in the implementation we send one NAV per uplink, in the case of single frame (single NAV message) you will have a position after the first uplink, in the case of multi frame you will have the position once the NAV group completely sent to the application server.

Today we don't have a "store and forward' implemention, we do the assumption that we are under coverage, in a partial coverage the application has to implement a mechanism storing the GNSS scan and send them once under coverage

Benjamin
