### ISSUE TITLE
LBM Geolocation SDK

### ISSUE THREAD

**Issue by matsujirushi** [Lora-net/SWSD004#6]
Hi,
I'm using the LBM Geolocation SDK.
In v3.0.0, the repository has been changed from "LBM Geolocation SDK" to "Tracker reference design". 🤔

* [README of v1.3.0](https://github.com/Lora-net/SWSD004/blob/v1.3.0/README.md)
* [README of v3.0.0](https://github.com/Lora-net/SWSD004/blob/v3.0.0/README.md)

Did it move to other repository???

**Comment by matsujirushi** [comment]
Has the Geolocation SDK been moved here?
https://github.com/Lora-net/SWL2001/tree/master/lbm_lib/smtc_modem_core/geolocation_services

**Comment by smtcbboulet** [comment]
Hello, SWSD004 now supports only the lora edge tracker reference design hardware but geolocation services are directly embedeed in LoRa Basics Modem. 
https://github.com/Lora-net/SWSD004/tree/master/lora_basics_modem/lora_basics_modem/lbm_lib/smtc_modem_core/geolocation_services
or as you mentionned here : https://github.com/Lora-net/SWL2001/tree/master/lbm_lib/smtc_modem_core/geolocation_services

If you want to run the geolocation example on a Nucleo Board + Shieldn there is an example right here : https://github.com/Lora-net/SWL2001/tree/master/lbm_applications/3_geolocation_on_lora_edge

**Comment by matsujirushi** [comment]
Thank you for answer!
